version: "3.2"
services:
  portal:
    build: './php-apache/'
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "88:80"
    volumes:
      - ../:/var/www/html/
  mysql:
    image: mysql/mysql-server:5.5
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${LOCAL_MYSQL_ROOT_PASSWORD}
networks:
  frontend:
  backend:
